### ISSUE TITLE
Error on MacOS

### ISSUE THREAD

**Issue by 4193883-eng** [undera/pylgbst#115]
I have this problem 

> ERROR:bleak.backends.corebluetooth.scanner:macOS 12 requires non-empty service_uuids kwarg, otherwise no advertisement data will be received

Is there any way to fix it?

**Comment by undera** [comment]
I have no idea how to deal with this. Maybe somebody in the community will be able to figure it out.

**Comment by 4193883-eng** [comment]
@undera maybe I should post it in bleak github?

**Comment by undera** [comment]
Feel free. Maybe that would give any hints...

**Comment by 4193883-eng** [comment]
the problem is macOS doesn't want you to use bluetooth in cli programmes, so to use bleak we need to use py2app
