### ISSUE TITLE
How to get Sound Files with Lego Boost app?

### ISSUE THREAD

**Issue by JaeYoungLee79** [undera/pylgbst#126]
Dear Sir

Did you try to get Sound Files with Lego Boost app?

I copy all file from my phone and check to path with audio.

I could not find it.

Have you experienced that?

Best Regards
Thanks

**Comment by undera** [comment]
Hi,
This project is about Python programming for Lego Boost, and I don't know much about mobile app from Lego. 
Try approaching Lego support, maybe they can help.
