### ISSUE TITLE
How to connect boost on my MAC?

### ISSUE THREAD

**Issue by jinhefeng** [undera/pylgbst#17]
Thanks fo your notice!

**Comment by undera** [comment]
You question is too vague. You give no context, no info on what you've tried and what observed. I can't help with no inputs.

**Comment by undera** [comment]
Looks like you did not install any backend libraries. Read here: https://github.com/undera/pylgbst#bluetooth-backend-prerequisites

**Comment by jinhefeng** [comment]
Failed to install gattlib and it seems no perfect solution.
I have watched your video in Youtube, how can you run it on MAC?

**Comment by undera** [comment]
I don't use Mac. I use Linux.
It's been reported by other users that they successfully run it on Mac, installing one of backend libraries. Please read through past issues.
