### ISSUE TITLE
Connect to specific Bluetooth Device Address

### ISSUE THREAD

**Issue by FloMiau** [undera/pylgbst#19]
Hey there,

so I'm looking for a way to connecto to a specific hub. I noted the Bluetooth Device Address / hub mac.

Now I'm trying to connect to the hub with the mac address. Sadly I couldn't find documentation for that.

I think I should to it this way:

```connection = get_connection_auto(hub_mac='aa:bb:cc:dd')```

But when I look at the code I think there are some flaws, for example at https://github.com/undera/pylgbst/blob/master/pylgbst/comms/cpygatt.py#L24:L44

I think it shouldn't be  ```if name == LEGO_MOVE_HUB or hub_mac == address:```  because at that logic it will connect me to the first hub that it detects and not to the one selected.

Please add some documentation to connect to a hub with a specific mac address.

Thank you.

**Comment by undera** [comment]
Hi,
You are right, the code has problem. I have committed the fix for it right away. Can you try with fix?

**Comment by FloMiau** [comment]
Hi. 
I've got only one hub so I can't really check.
I've got a question. Why do you scan and iterate over the results? I think you can conenct directly to that address.

Maybe this will work, too?
```
    def connect(self, hub_mac=None):
        log.debug('GattoolConnection: connect')
        log.debug("Trying to connect client to MoveHub with MAC: %s", hub_mac)
        adapter = self.backend()
        adapter.start()

        if hub_mac is not None:
            log.info("Connect to %s", hub_mac)
            self._conn_hnd = adapter.connect(hub_mac)
        else:
            while not self._conn_hnd:
                log.info("Discovering devices...")
                devices = adapter.scan(1)
                log.debug("Devices: %s", devices)

                for dev in devices:
                    address = dev['address']
                    name = dev['name']
                    if name == LEGO_MOVE_HUB:
                        log.info("Found %s at %s", name, address)
                        self._conn_hnd = adapter.connect(address)
                        break

                if self._conn_hnd:
                    break

        return self
```

**Comment by undera** [comment]
Does it work that way for you?

**Comment by undera** [comment]
Is it different with the poll code?
