### ISSUE TITLE
Rotating  A & B motors to turn wheels

### ISSUE THREAD

**Issue by aphadke19** [undera/pylgbst#20]
First of all, Thank you very much for the wonderful repo and very gracious notes on how to get things working. I do have this setup working with a Lego boost.

I m now stuck on a problem where I have a bare-bones move-hub with wheels for motor A & B and trying to get the bot to turn right/left. I tried using the angled methods, but looks like they refer to the angle of rotation, not turning the wheel to the left or right. Lego boost app does have an operation to turn left/right on the hub, hence wondering if there is an API that I have overlooked, or if you have any insight into how else to achieve this.

Thanks
Amit

**Comment by undera** [comment]
Can you show your piece of code?

**Comment by aphadke19** [comment]
I m simply using your snippets.

`from pylgbst.movehub import MoveHub`
`hub = MoveHub()`
`hub.motor_AB.angled(90, 0.8)`

**Comment by undera** [comment]
Read here: https://github.com/undera/pylgbst#controlling-motors
Specifically, there is note there `Note: In group angled mode, total rotation angle is distributed across 2 motors according to motor speeds ratio.`

There is one more parameter to `angled()` method, it sets the separate speed for second motor in pair. So if you will specify something like `hub.motor_AB.angled(90, 0.8, 0.3)`, your bot will rotate motors differently, causing bot to turn.
