### ISSUE TITLE
Document installation requirements/supported configurations

### ISSUE THREAD

**Issue by askvictor** [undera/pylgbst#3]
This appears to require gattlib installed first - this should be listed in the README or added to requirements or module dependencies. In turn, gattlib doesn't seem to support Windows - this should be documented as well.

**Comment by undera** [comment]
It is listed in module dependencies, look here: https://github.com/undera/pylgbst/blob/master/setup.py#L9

**Comment by undera** [comment]
I have added a note about windows unsupported
