### ISSUE TITLE
Cannot read SPEED of boost motor

### ISSUE THREAD

**Issue by nakermann1973** [undera/pylgbst#39]
peripherals.py, line 242 is

    speed = unpack("<b", data[0])[0]

This line returns an error when subscribing to the SPEED sensor.

Changing it to 

    speed = unpack("<b", data[0:4])[0]

appears to fix the problem, but I don't know if that is correct in all cases

**Comment by undera** [comment]
Thanks for reporting, this is a bug. The correct fix is to have `data[0:1]` or just `data`, since the value is single-byte
