### ISSUE TITLE
Instable Communication using BLED112 (BlueGiga) Dongle under Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by StefanMack** [undera/pylgbst#57]
Hi Andrey,

thanks a lot for this fabulous package!
I have been using you code now for quite a while. First on Windows 7 and Raspian and now on Ubuntu 18.04 LTS.
With Ubuntu the BLED112-Dongle first did not work. It took me some time to find out, that the default reset of the dongle in pygatt.bakcends.bgapi.py in the method BGAPIBackend.start(reset=True) was the reason for the malfunction.
In my case I changed the above method in the pygatt package to BGAPIBackend.start(reset=False) and now everything works fine. Both with the BLED112 and with a tp-link UB400 (real) BLE-Dongle.
Maybe there is a way I did not see to set the flag reset=False not in the pygatt but in the pylgbst package?
By the way: 
1) Recently I had an old MoveHub with firmware 0.0.00.0223. I had to update the Lego Firmware to 2.0.00.0017 for the MoveHub to cooperate with your package.
2) A student of mine currently uses your package for implementing ROS with Lego Boost.

Best regards and thank you again.
Stefan

**Comment by undera** [comment]
Hello Stefan,

Can you create a PR with the fix? I myself don't have neither Windows nor BLE112, so I can't debug this code.
