### ISSUE TITLE
INFO:comms-gatt:Discovering devices...

### ISSUE THREAD

**Issue by Dmole** [undera/pylgbst#58]
The LED on my Bluetooth dongle will light up when I use bluetoothctl or gatttool (which successfully drives the Lego motors).

But when I run the example code it reports "Discovering devices..." forever and the LED on the dongle stays dark.

Maybe it's because the USB dongle has 2 Controllers, Any ideas how to make pylgbst try more than the first Controller?

(also control-c and control-d fail to be respected.)

**Comment by undera** [comment]
Every connection object and function has a parameter, where you can put name of controller. Usually, default name is `hci0`. Look here for code example: https://github.com/undera/pylgbst#bluetooth-connection-options
