### ISSUE TITLE
Faulty connection/LED Raspberry Pi 4

### ISSUE THREAD

**Issue by M11R05** [undera/pylgbst#61]
Hello Undra,

thanks for creating and supporting the pylgbst libary!
I'm working with a new Raspberry Pi 4B and the latest raspian image and latest version of pylgbst. The system is updated.

I've problems to get the Move Hub run with the Raspi. It starts with the gattlib and bluepy libaries.
[bluetooth_log.txt](https://github.com/undera/pylgbst/files/4684934/bluetooth_log.txt)

In your demo.py I've allready added the mac of the hub manually, please see picture:
![Move Hub mac](https://user-images.githubusercontent.com/65979581/82948388-f9ef9300-9fa1-11ea-8447-b16580f24c5f.JPG)
I'm a green horn when it comes to python and hope it's in the right place.

My problem is, that the Raspi seems to connect with the Move Hub and gets its status, but then it starts to search again for ble devices and after a while the system freezes and I have to restart it.  But the hub seems still to be connected because the leds are one and it doesn't switch of. Please see the log of the demo.py:
[demo_py log.txt](https://github.com/undera/pylgbst/files/4684956/demo_py.log.txt)

I hope you can help me. Thanks!

**Comment by undera** [comment]
Hi
The problem in your code is that you are trying to create MoveHub() object twice.

You need to remove either line 253 or line 260.

**Comment by M11R05** [comment]
Hello Undera,

thanks a lot, it worked! The motors are working, tilt sensors seem to correspond and distance is detetcted.
There is only one issue with the LED. They are supposed to change color but there seems to be a problem within the code. Please see my log:
[RGB log.txt](https://github.com/undera/pylgbst/files/4689945/RGB.log.txt)
Could you give me a hind how to fix it?

Thanks Matthias!

**Comment by undera** [comment]
It looks like you have subscribed to LED notifications and subscriber function misses the required parameter. Can you show the code you run?

**Comment by M11R05** [comment]
Here it is:
[demo.txt](https://github.com/undera/pylgbst/files/4689995/demo.txt)

**Comment by undera** [comment]
`def colour_callback(**named):` is wrong. do it as `def colour_callback(named):`

**Comment by M11R05** [comment]
Now its working as its supposed to be.
Thanks a lot for the quick and good support!
