### ISSUE TITLE
It doesnt work on Raspberry pi

### ISSUE THREAD

**Issue by FuchsCrafter** [undera/pylgbst#74]
It doesent work on my Rpi 4 model b (Thonny Python IDE).
There is just an error message (in the Demo file):

Traceback (most recent call last):
  File "/home/pi/Downloads/boost/pylgbst-master/examples/demo.py", line 5, in <module>
    from pylgbst import *
ModuleNotFoundError: No module named 'pylgbst'

![pyglst](https://user-images.githubusercontent.com/69680700/92121180-4563d980-edfa-11ea-9465-85254265b962.png)

and i cant install bluepy

![image](https://user-images.githubusercontent.com/69680700/92122019-3e899680-edfb-11ea-916f-c66359eaa8df.png)

 Why it is so and what can i do?

**Comment by undera** [comment]
`No module named...` is pretty basic Python exception, it means Python interpreted is unable to find the library. There can be various reasons for that: you did not install module, module search paths are not configured properly, etc.

**Comment by FuchsCrafter** [comment]
> `No module named...` is pretty basic Python exception, it means Python interpreted is unable to find the library. There can be various reasons for that: you did not install module, module search paths are not configured properly, etc.

And what can I so?

**Comment by reinhard-brandstaedter** [comment]
Try:
```pip3 install pyglbst``` to install the pyglbst module. Depending how you run you might do it as root

**Comment by FuchsCrafter** [comment]
Thanks. I will try it.

**Comment by FuchsCrafter** [comment]
It works now. Issue closed.

PS Now I thing im not a big brain.
