### ISSUE TITLE
Hub (88009) to control train motors

### ISSUE THREAD

**Issue by pdcemulator** [undera/pylgbst#80]
Hi,

I want to automate train motors. So I only have a Hub (88009) and motor (88011). Will this be enough to control the motor or do I need the Move Hub (8806)?

The docs only describes the Move Hub but there is a GenericHub class... Maybe this one will work? I am not able to test because I still have to buy the equipment.

Thank you for advise

**Comment by undera** [comment]
Yes, generic hub will work. There is a prototype of TrainHub class, you might contribute improvements for it if you are proficient in Python.

**Comment by pdcemulator** [comment]
Great, thank you.
I have some basic Python skills, maybe I'm able to contribute.
