### ISSUE TITLE
touch objects and reference motors

### ISSUE THREAD

**Issue by Pippsen** [undera/pylgbst#84]
Hello,

if I drive against objects with the code below, I never get a "done" or even a failure. The idea was to touch an object ad with this I can take a reference for my drive. For protect the motor as well the mechanics, I adjust the speed and the force to a low level.

`from pylgbst import get_connection_bluegiga
from pylgbst.hub import MoveHub

hub = MoveHub(get_connection_bluegiga(hub_mac='00:16:53:a2:48:6F'))

hub.motor_A.angled(20, 0.1, None, 0.2)
print('Done 20 degrees')
hub.motor_A.angled(-20, 0.1, None, 0.2)
print('Done -20 degrees')`

Is there any possibility to get again access to the drive?

**Comment by undera** [comment]
When you use "angled" rotation commands, the motor "completes" the command only when desired degrees are rotated. Change your rotation commands to "timed" and it will return after certain time.
