### ISSUE TITLE
README too pessimistic about Windows support

### ISSUE THREAD

**Issue by antoinechauveau** [undera/pylgbst#90]
The following mention about Windows support is too pessimistic, either scaring away potential Windows users or getting them to buy unnecessary hardware:

> Running on Windows requires Bluegiga BLED112 Bluetooth Smart Dongle hardware piece, because no other hardware currently works on Windows with Python+BLE.

The Bleak backend was introduced specifically to avoid this strict HW dependency, as stated in https://github.com/undera/pylgbst/pull/54. Taking it into use with the internal Bluetooth support of my aging Asus N76VZ laptop running Windows 10 20H2 was seamless.

I recommend softening this statement, it could help expand the user base for this project.

**Comment by undera** [comment]
Feel free to suggest PR with update of README, according to your Windows experience. I have only Linux, sorry
